services:
  _defaults:
    autowire:       true
    autoconfigure:  true
    public:         true


##### Services
  Austral\ElasticSearchBundle\Services\ElasticSearch: "@austral.elastic_search"
  austral.elastic_search:
    class: Austral\ElasticSearchBundle\Services\ElasticSearch
    arguments:
      - "@service_container"
      - "@event_dispatcher"
      - "@austral.entity_manager"
      - "@austral.elastic_search.config"
      - "@austral.entity.mapping"

  Austral\ElasticSearchBundle\Configuration\ElasticSearchConfiguration: "@austral.elastic_search.config"
  austral.elastic_search.config:
    class:        Austral\ElasticSearchBundle\Configuration\ElasticSearchConfiguration
    arguments:
      - "%austral_elastic_search_config%"

##### Austral Listener
  Austral\ElasticSearchBundle\Listener\EntityMappingListener: "@austral.elastic_search.entity_mapping.listener"
  austral.elastic_search.entity_mapping.listener:
    class:        Austral\ElasticSearchBundle\Listener\EntityMappingListener
    arguments:
      - "@service_container"
    tags:
      - { name: kernel.event_listener, event: "austral.event.entity.initialise.mapping", method: mapping }

  Austral\ElasticSearchBundle\Listener\DoctrineListener:  "@austral.elastic_search.doctrine.listener"
  austral.elastic_search.doctrine.listener:
    class:        Austral\ElasticSearchBundle\Listener\DoctrineListener
    arguments:
      - "@austral.elastic_search"
      - "@austral.elastic_search.config"
    tags:
      - { name: doctrine.event_subscriber, connection: default }

##### Austral Event Subscriber
  Austral\ElasticSearchBundle\EventSubscriber\ElasticSearchEventSubscriber: "@austral.elastic_search.event_subscriber"
  austral.elastic_search.event_subscriber:
    class:        Austral\ElasticSearchBundle\EventSubscriber\ElasticSearchEventSubscriber
    tags:
      - { name: kernel.event_subscriber}

  Austral\ElasticSearchBundle\EventSubscriber\ElasticSearchHydrateObjectEventSubscriber:  "@austral.elastic_search.hydrate_object.event_subscriber"
  austral.elastic_search.hydrate_object.event_subscriber:
    class:        Austral\ElasticSearchBundle\EventSubscriber\ElasticSearchHydrateObjectEventSubscriber
    tags:
      - { name: kernel.event_subscriber}

  Austral\ElasticSearchBundle\EventSubscriber\ElasticSearchSelectObjectsEventSubscriber:  "@austral.elastic_search.select_objects.event_subscriber"
  austral.elastic_search.select_objects.event_subscriber:
    class:        Austral\ElasticSearchBundle\EventSubscriber\ElasticSearchSelectObjectsEventSubscriber
    tags:
      - { name: kernel.event_subscriber}